version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ broker port
      - "15672:15672"  # Management plugin web interface
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Default username
      RABBITMQ_DEFAULT_PASS: guest  # Default password
      RABBITMQ_DEFAULT_VHOST: /  # Default virtual host
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent data storage
      - rabbitmq_logs:/var/log/rabbitmq  # Logs

volumes:
  rabbitmq_data:
  rabbitmq_logs:
